version: "3.8"

services:
  coreui-react:
    container_name: coreui-react
    build: .
    ports:
      -  "5176:3000"
    volumes:
      - /data/snapology-dashboard-dev/logs:/app/logs
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
